name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pangolin
  - usher
  - pip:
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
