on:
  pull_request:
    branches:
    - main
name: Test Podman
jobs:
  test:
    name: Test Podman
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create artifacts dir to save test logs
      run: mkdir artifacts
    - name: Install Podman
      run: bash .github/scripts/install_podman.sh
    - name: Install Nextflow
      run: bash .github/scripts/install_nextflow.sh
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test_artifacts
        path: artifacts
